// Barrel export for document sections

export { buildCoverPage } from './coverPage';
export { buildExecutiveSummary } from './executiveSummary';
export { buildAssumptionsAndScope } from './assumptions';
export { buildEnvironmentAnalysis } from './environmentAnalysis';
export { buildMigrationReadiness } from './migrationReadiness';
export { buildMigrationOptions } from './migrationOptions';
export { buildMigrationStrategy } from './migrationStrategy';
export { buildROKSOverview } from './roksOverview';
export { buildVSIOverview } from './vsiOverview';
export { buildCostEstimation } from './costEstimation';
export { buildDay2OperationsSection } from './day2Operations';
export { buildNextSteps } from './nextSteps';
export { buildAppendices } from './appendices';
export { buildRiskAssessmentSection } from './riskAssessment';
export { buildTimelineSection } from './timelineEstimation';
export { buildNetworkDesignSection } from './networkDesign';
export { buildPlatformSelectionSection } from './platformSelection';
export { buildComplexityAssessment } from './complexityAssessment';
export { buildOSCompatibilitySection } from './osCompatibility';
export { buildWorkloadClassification } from './workloadClassification';
export { buildPlatformRecommendation } from './platformRecommendation';
export { buildSourceBOMSection } from './sourceBom';
