export { addTitleSlide } from './titleSlide';
export { addImageSlide } from './imageSlide';
export { addAgendaSlide } from './agendaSlide';
export { addExecutiveSummarySlide } from './executiveSummary';
export { addMigrationStatsSlide, addRemediationActionsSlide } from './migrationStatsSlide';
export { addExcludedVMsSlide } from './excludedVMsSlide';
export { addPlatformRecommendationSlide } from './platformRecommendation';
export { addCostEstimationSlide } from './costEstimation';
export { addWavePlanningSlide } from './wavePlanningSlide';
export { addMigrationExecutionSlide } from './migrationExecutionSlide';
export { addNextStepsSlide } from './nextSteps';
