// AI Report Preview — shows AI-generated report sections before export

import {
  Tile,
  Tag,
  InlineLoading,
  InlineNotification,
  Button,
  Tabs,
  TabList,
  Tab,
  TabPanels,
  TabPanel,
} from '@carbon/react';
import { Renew } from '@carbon/icons-react';
import type { ReportNarrativeResult } from '@/services/ai/types';

interface AIReportPreviewProps {
  narrative: ReportNarrativeResult | null;
  isLoading: boolean;
  error: string | null;
  onRefresh?: () => void;
}

export function AIReportPreview({
  narrative,
  isLoading,
  error,
  onRefresh,
}: AIReportPreviewProps) {
  if (isLoading) {
    return (
      <Tile>
        <InlineLoading status="active" description="Generating report narratives..." />
      </Tile>
    );
  }

  if (error) {
    return (
      <InlineNotification
        kind="error"
        title="AI Report"
        subtitle={error}
        lowContrast
        hideCloseButton
      />
    );
  }

  if (!narrative) {
    return null;
  }

  return (
    <div className="ai-report-preview">
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
        <h4>AI-Generated Report Sections</h4>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <Tag type="purple" size="sm">AI</Tag>
          {onRefresh && (
            <Button kind="ghost" size="sm" renderIcon={Renew} iconDescription="Refresh" hasIconOnly onClick={onRefresh} />
          )}
        </div>
      </div>

      <Tabs>
        <TabList aria-label="Report sections">
          <Tab>Executive Summary</Tab>
          <Tab>Environment</Tab>
          <Tab>Recommendation</Tab>
          <Tab>Risks</Tab>
          <Tab>Costs</Tab>
          <Tab>Next Steps</Tab>
        </TabList>
        <TabPanels>
          <TabPanel>
            <NarrativeSection content={narrative.executiveSummary} />
          </TabPanel>
          <TabPanel>
            <NarrativeSection content={narrative.environmentAnalysis} />
          </TabPanel>
          <TabPanel>
            <NarrativeSection content={narrative.migrationRecommendation} />
          </TabPanel>
          <TabPanel>
            <NarrativeSection content={narrative.riskNarrative} />
          </TabPanel>
          <TabPanel>
            <NarrativeSection content={narrative.costJustification} />
          </TabPanel>
          <TabPanel>
            {narrative.nextSteps.length > 0 && (
              <div>
                <h5 style={{ marginBottom: '0.5rem' }}>Next Steps</h5>
                <ol>
                  {narrative.nextSteps.map((step, i) => <li key={i}>{step}</li>)}
                </ol>
              </div>
            )}
            {narrative.assumptions.length > 0 && (
              <div style={{ marginTop: '1rem' }}>
                <h5 style={{ marginBottom: '0.5rem' }}>Key Assumptions</h5>
                <ul>
                  {narrative.assumptions.map((a, i) => <li key={i}>{a}</li>)}
                </ul>
              </div>
            )}
          </TabPanel>
        </TabPanels>
      </Tabs>

      <Tag type="warm-gray" size="sm" style={{ marginTop: '0.5rem' }}>
        Generated by IBM watsonx.ai — review and edit before distribution
      </Tag>
    </div>
  );
}

function NarrativeSection({ content }: { content: string }) {
  if (!content) {
    return <p style={{ color: 'var(--cds-text-placeholder)' }}>No content generated</p>;
  }
  return (
    <div>
      {content.split('\n\n').map((paragraph, i) => (
        <p key={i} style={{ marginBottom: '0.75rem' }}>{paragraph}</p>
      ))}
    </div>
  );
}
